DROP TABLE IF EXISTS deals CASCADE;
CREATE TABLE deals (
    id SERIAL PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    URL VARCHAR(1000) NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);


-- DROP TABLE IF EXISTS liked CASCADE;
-- CREATE TABLE liked (
--   id SERIAL PRIMARY KEY NOT NULL,
--   user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
--   deal_id INTEGER REFERENCES deals(id) ON DELETE CASCADE
-- );



