CREATE TABLE likes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  deals_key INTEGER REFERENCES deals(id) ON DELETE CASCADE
);

CREATE TABLE ratings (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  deals_id INTEGER REFERENCES deals(id) ON DELETE CASCADE,
  rating_value INTEGER
);

CREATE TABLE comments (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  deals_id INTEGER REFERENCES deals(id) ON DELETE CASCADE,
  message TEXT
  date_added
);